
- label: "What You'll Learn"
  name: "learn"
  widget: "list"
  required: false
  allow_add: true
  collapsed: false
  field:
    label: "Add one point"
    name: "item"
    widget: "string"
    hint: "Write ONE point only (not a paragraph)"

- label: "Who Should Attend?"
  name: "who"
  widget: "list"
  required: false
  field:
    label: "Add one person/group"
    name: "item"
    widget: "string"
    hint: "Write ONE item only"

- label: "Workshop Outcomes"
  name: "outcomes"
  widget: "list"
  required: false
  field:
    label: "Add one outcome"
    name: "item"
    widget: "string"
    hint: "Write ONE result only"
