backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "events"
    label: "Events"
    files:
      - name: "events"
        label: "All Events"
        file: "content/events.json"
        format: "json"
        fields:
          - label: "Events"
            name: "events"
            widget: "list"
            fields:
              - label: "Title"
                name: "title"
                widget: "object"
                fields:
                  - { label: "Arabic", name: "ar", widget: "string", required: false }
                  - { label: "English", name: "en", widget: "string" }

              - label: "Date"
                name: "date"
                widget: "datetime"

              - label: "Image"
                name: "image"
                widget: "image"
                required: false

              - label: "Format"
                name: "format"
                widget: "object"
                required: false
                fields:
                  - { label: "Arabic", name: "ar", widget: "string", required: false }
                  - { label: "English", name: "en", widget: "string", required: false }

              - label: "Facilitator"
                name: "facilitator"
                widget: "object"
                required: false
                fields:
                  - { label: "Arabic", name: "ar", widget: "string", required: false }
                  - { label: "English", name: "en", widget: "string", required: false }

              - label: "About"
                name: "about"
                widget: "object"
                required: false
                fields:
                  - { label: "Arabic", name: "ar", widget: "text", required: false }
                  - { label: "English", name: "en", widget: "text", required: false }

              - label: "What You'll Learn"
                name: "learn"
                widget: "object"
                required: false
                fields:
                  - label: "Arabic"
                    name: "ar"
                    widget: "list"
                    required: false
                    allow_add: true
                    collapsed: false
                    field:
                      label: "Add one point"
                      name: "item"
                      widget: "string"

                  - label: "English"
                    name: "en"
                    widget: "list"
                    required: false
                    allow_add: true
                    collapsed: false
                    field:
                      label: "Add one point"
                      name: "item"
                      widget: "string"

              - label: "Who Should Attend?"
                name: "who"
                widget: "object"
                required: false
                fields:
                  - label: "Arabic"
                    name: "ar"
                    widget: "list"
                    required: false
                    field:
                      label: "Add one person/group"
                      name: "item"
                      widget: "string"

                  - label: "English"
                    name: "en"
                    widget: "list"
                    required: false
                    field:
                      label: "Add one person/group"
                      name: "item"
                      widget: "string"

              - label: "Workshop Outcomes"
                name: "outcomes"
                widget: "object"
                required: false
                fields:
                  - label: "Arabic"
                    name: "ar"
                    widget: "list"
                    required: false
                    field:
                      label: "Add one outcome"
                      name: "item"
                      widget: "string"

                  - label: "English"
                    name: "en"
                    widget: "list"
                    required: false
                    field:
                      label: "Add one outcome"
                      name: "item"
                      widget: "string"

              - label: "Facilitator Bio"
                name: "facilitatorBio"
                widget: "object"
                required: false
                fields:
                  - { label: "Arabic", name: "ar", widget: "text", required: false }
                  - { label: "English", name: "en", widget: "text", required: false }

              - label: "Fee"
                name: "fee"
                widget: "object"
                required: false
                fields:
                  - { label: "Arabic", name: "ar", widget: "string", required: false }
                  - { label: "English", name: "en", widget: "string", required: false }

              - label: "Translation"
                name: "translation"
                widget: "object"
                required: false
                fields:
                  - { label: "Arabic", name: "ar", widget: "string", required: false }
                  - { label: "English", name: "en", widget: "string", required: false }

              - label: "Register Link"
                name: "register"
                widget: "string"
                required: false
                default: "#"